### ISSUE TITLE
Check permissions on other pages than viewtopic and posting

### ISSUE THREAD

**Issue by Galixte** [VSEphpbb/abbc3#18]
Hi,

whith Ajax Chat extension, the BBCodes permissions are not checked on index.php page and Chat center page /chat.

Could you take a look? https://github.com/LMOspaceace/ajaxchat/issues/39

**Comment by VSEphpbb** [comment]
BBCodes permissions???

Not sure what you mean, but I can tell you everything this extension does with BBCode usage happens within phpBB's bbcode engine, so any issues you are seeing will be a problem that extension is causing.

**Comment by VSEphpbb** [comment]
oh i see... that extension is using their own bbcodes script. if they use phpbb's post butttons script it would work. but they dont so it will not work with that ext.
