### ISSUE TITLE
Can't install plugin on 3.1.5

### ISSUE THREAD

**Issue by jrmiller82** [VSEphpbb/abbc3#19]
I've followed your install suggestions and nothing pops up in the extension manager? Any thoughts? Other extensions have installed just fine.

**Comment by jrmiller82** [comment]
Well that's real nice... just close the issue like there's nothing wrong? Gee, thanks.

**Comment by VSEphpbb** [comment]
Well, there's no issue here.

Download the extension from phpBB.com (link is on main page) and if you need support use the support forums for this extension on phpBB.com.
