### ISSUE TITLE
We universal dropdown menu for police types and size

### ISSUE THREAD

**Issue by Galixte** [VSEphpbb/abbc3#20]
Hi @VSEphpbb,

With this extension, the texts of dropdown menus for Police types and Police sizes are not displayed correctly for it’s height. See that: http://www.ezcom-fr.com/download/file.php?id=386

I think there is the padding top/bottom for the class ```select,
.inputbox``` in forms.css that it should be at 2px instead of 4px.

should i submit to the style author this issue ?

**Comment by VSEphpbb** [comment]
It looks like I should fix that. Horizontal padding in those select menus should be 0.

**Comment by Galixte** [comment]
Thanks fixed here: https://github.com/VSEphpbb/abbc3/commit/20c69245c52320c11d2a9ca2917f6e45af8d51e5.
