### ISSUE TITLE
twitch failed to load

### ISSUE THREAD

**Issue by P4InKiLL3R** [VSEphpbb/abbc3#33]
Hallo,

bei mir Funktionieren die Twitch Streams nicht in meinem php bb Forum!

http://fs5.directupload.net/images/161025/npnwhh2c.png

Nutze Deine Ext. schon eine ganze weile wo der Fehler uns nie aufgefallen ist 
und jetzt wo wir ein paar Streamer bei uns haben sind wir darauf gestoßen!

Habe auf Deine neue Version upgedatet aber der Fehler besteht weiterhin ;/

Woran kann das liegen?

MfG

**Comment by VSEphpbb** [comment]
Twitch works fine for me. The problem was with Twitch itself it appears.

![screen shot 2016-10-25 at 8 41 08 am](https://cloud.githubusercontent.com/assets/303711/19692985/cc5f7250-9a8e-11e6-9488-c622c8b2aafa.png)

Also, that screenshot does not appear to be this extension.
