### ISSUE TITLE
custom icon not displaying (3.1.4-dev)

### ISSUE THREAD

**Issue by bcurran3** [VSEphpbb/abbc3#34]
crosslink : https://www.phpbb.com/customise/db/extension/advanced_bbcode_box/support/topic/171906

RE: https://www.phpbb.com/customise/db/exte ... x/faq/1551
How Do I Add an Icon To My Custom BBCodes?

Easy! All you need is an icon in GIF format that has the exact same name as your BBCode.

Just add the icon to the vse/abbc3/images/icons/ directory.

For example, the BBCode [foobar][/foobar] would work with foobar.gif.

For convenience, ABBC3 ships with a huge library of icons that you can find in the vse/abbc3/contrib/ directory.

If you want to create your own icons, ABBC3 uses 16x16 GIF icons.
So I added a Google search BBcode.

BBCode usage:
[google]{INTTEXT}[/google]

HTML replacement:
<input class="button2 btnlite" type="button" value='Google: {INTTEXT}'""
onclick="window.location.href='http://www.google.com/search?q={INTTEXT}'" />

Help line:
Google search: [google]keyword(s)[/google]

and I put google.gif in:
\ext\vse\abbc3\images\icons
google.gif
google.gif (1.04 KiB) Viewed 6 times
(You can add to contrib if you want.)

...but even after clearing cache on two browsers and connecting to the board using a browser that has never connected before, I get:
Untitled.png
Untitled.png (3.59 KiB) Viewed 7 times
(picture of button with the word "google" on it)
Bug?

phpBB 3.2 / abbc 3.1.4-dev

p.s. Can anyone more knowledgeable than me tell me how to make that HTML replacement code open in a new tab/window?

**Comment by Galixte** [comment]
Hi @bcurran3,

https://www.phpbb.com/customise/db/extension/advanced_bbcode_box/faq/1551

Your image icon must have 16x16px as size.

**Comment by bcurran3** [comment]
FYI-1: All current defaults in the extension are 20x20.
FYI-2: He updated the FAQ to "If you want to create your own icons, ABBC3 uses 16x16 and 20x20 GIF icons."
FYI-3: My google.gif 20x20 is working now, yeah!
