### ISSUE TITLE
Width Problem

### ISSUE THREAD

**Issue by LuigiMdg** [VSEphpbb/abbc3#41]
Hi..
I've this problem:
![image](https://user-images.githubusercontent.com/18232125/34701533-21e5f8c4-f4e9-11e7-99a2-3d1194f3021c.png)
Example url: https://pronosticiippica.it/pronostici-trotto-f14/napoli-09-01-2018-18-30-corsa-7-agnano-t1083.html#p1026

**Comment by VSEphpbb** [comment]
what problem?

**Comment by LuigiMdg** [comment]
The width of the text editor.. If I edit with width 100%, they take this edit to the complete editor..

**Comment by VSEphpbb** [comment]
this extension has nothing to do with that. That's either part of phpBB or some other quick reply extension.
