### ISSUE TITLE
youtube/bbvideo video embedded twice

### ISSUE THREAD

**Issue by jamiroconca** [VSEphpbb/abbc3#42]
hi,

i'm facing an issue with the youtube/bbvideo bbcode, these are the settings
`[youtube]{URL}[/youtube]`
->
`<a href="{URL}" class="bbvideo" data-bbvideo="560,315">{URL}</a>`

phpbb version: 3.2.1
Advanced BBCode Box version: 3.1.4

this is an example of the results:
`<div class="content"><div><div><a href="http://it.youtube.com/watch?v=YOUTUBEVIDEOCODE" class="bbvideo" data-bbvideo="560,315">http://it.youtube.com/watch?v=YOUTUBEVIDEOCODE</a></div><iframe width="453" height="254.8125" src="//www.youtube.com/embed/YOUTUBEVIDEOCODE" frameborder="0" allowfullscreen=""></iframe></div><iframe width="453" height="254.8125" src="//www.youtube.com/embed/YOUTUBEVIDEOCODE" frameborder="0" allowfullscreen=""></iframe></div>`

looks like there's an additional iframe outside the bbcode substitution

**Comment by VSEphpbb** [comment]
Embedding is handled now by a 3rd party library, not by ABBC3
